version: 2.1

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6

    steps:
      - checkout

      - run:
          name: Capture git tree SHA before deleting repository
          command: |
            echo "export TREE_SHA1=$(git log -1 --pretty=format:'%T')" >> $BASH_ENV

      - run:
          name: Delete local git repository
          command: rm -rf .git

      - run:
          name: Install dependencies
          command: |
            gem install bundler -v2.1.4
            bundle install --jobs=4 --retry=3 --path vendor/bundle

      - run:
          name: Run tests
          command: bin/rspec

      - run:
          when: always # Run this step even when the tests fail
          name: Send test results to BuildPulse
          command: |
            curl -fsSL https://github.com/buildpulse/test-reporter/releases/latest/download/test-reporter-linux-amd64 > ./buildpulse-test-reporter
            chmod +x ./buildpulse-test-reporter
            ./buildpulse-test-reporter submit spec/reports --account-id 68192324 --repository-id 238705816 --tree $TREE_SHA1 # Replace IDs with your BuildPulse account ID and repository ID
