version: 2.1

orbs:
  buildpulse: workshop64/buildpulse@0.3

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6

    steps:
      - checkout

      - buildpulse/setup # Set up BuildPulse connection *before* running the test suite

      - run:
          name: Install dependencies
          command: |
            gem install bundler -v2.1.4
            bundle install --jobs=4 --retry=3 --path vendor/bundle

      - run:
          name: Run tests
          command: bin/rspec

      - buildpulse/upload:
          path: spec/reports
          account-id: 46661156 # Replace this value with your BuildPulse account ID
          repository-id: 238705816 # Replace this value with your BuildPulse repository ID
